spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:springcoredb;MODE=MySQL;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    me.silvernine: DEBUG

jwt:
  secret: 

server:
  error:
    include-message: always
